#!/usr/bin/env python3
"""Per-paper coverage report. For each past exam it (heuristically) detects the
sub-question labels present in the text dump, compares them with the labels
actually cited in data/*.json, and writes COVERAGE.md plus the compact
data/coverage-summary.json the site footer renders.

Detection is approximate (regex over the text dump), so treat the numbers as a
coverage *signal*, not ground truth — a 'missed' label is often merged into a
combined card or belongs to a figure-heavy question that was summarized."""
import glob, json, re, pathlib, sys

try:
    sys.stdout.reconfigure(encoding="utf-8", errors="replace")
except Exception:
    pass

ROOT = pathlib.Path(__file__).resolve().parent.parent
TXT = ROOT / "AK" / "_txt"
QUESTION_MANIFEST = ROOT / "data" / "exam-question-manifest.json"

# Coverage is reported over the 12 past papers only — exercise sheets are study
# material rather than something to be "covered".
EXAMS = {c: f"{c}.txt" for c in (
    "25EDC", "25RDC", "24EDC", "22EDC", "22RDC",
    "23ELI", "23RLI", "21EFB", "21RFB", "20EFB", "20RFB", "20MFB",
)}


def detect_labels(text):
    """Sub-question labels detected in a paper's text.

    Two numbering styles occur: Cremers papers print '3.1' at the start of a
    line, Bernard / Li papers print a 'Problem N' heading followed by 'a)',
    'b)' subparts (cited as '4a')."""
    labels = set()
    for m in re.finditer(r"(?m)^\s*(\d+)\.(\d+)(?=[\s)])", text):
        major, minor = m.group(1), m.group(2)
        # skip credit annotations like '0.5' / '1.0'
        if major != "0" and minor != "0":
            labels.add(f"{major}.{minor}")
    problem = None
    for line in text.splitlines():
        pm = re.match(r"^Problem\s+(\d+)\b", line)
        if pm:
            problem = pm.group(1)
            continue
        sm = re.match(r"^\s*([a-z])\)", line)
        if sm and problem:
            labels.add(f"{problem}{sm.group(1)}")
    return labels


def cited_labels():
    """Map paper code -> set of cited labels from the data JSON."""
    cited = {e: set() for e in EXAMS}
    for f in glob.glob(str(ROOT / "data" / "ch*.json")):
        if pathlib.Path(f).name == "chapters.json":
            continue
        data = json.loads(pathlib.Path(f).read_text(encoding="utf-8"))
        for kp in data["knowledge_points"]:
            for q in kp["questions"]:
                for s in q["sources"]:
                    m = re.match(r"^(\d\d[MER][A-Z]{2})\s+(\S+)$", s)
                    if m and m.group(1) in cited:
                        cited[m.group(1)].add(m.group(2))
    return cited


def main():
    cited = cited_labels()
    exact = (
        json.loads(QUESTION_MANIFEST.read_text(encoding="utf-8"))
        if QUESTION_MANIFEST.exists()
        else {}
    )
    rows, tot_det, tot_cov, detail = [], 0, 0, []
    for ex, fn in EXAMS.items():
        p = TXT / fn
        if ex in exact:
            det = set(exact[ex])
        elif not p.exists():
            continue
        else:
            det = detect_labels(p.read_text(encoding="utf-8", errors="ignore"))
        if not det:
            # scanned paper with no text layer — nothing to measure against
            continue
        cov = det & cited[ex]
        missed = sorted(det - cited[ex], key=lambda s: (s[0].isalpha(), s))
        pct = 100 * len(cov) / len(det)
        rows.append((ex, len(det), len(cov), pct))
        tot_det += len(det)
        tot_cov += len(cov)
        if missed:
            detail.append((ex, missed))

    overall = (100 * tot_cov / tot_det) if tot_det else 0
    lines = [
        "# Coverage report", "",
        "Auto-generated by `tools/coverage_report.py`. 'Detected' = sub-question labels "
        "found in the paper's text dump (or in the exact manifest where available); "
        "'Cited' = labels referenced by at least one card on the site. Regex detection "
        "is heuristic, so a 'missed' item may simply be "
        "merged into a combined card or summarized because it is figure-heavy. Scanned "
        "papers with no text layer are omitted.", "",
        "| Paper | Detected Qs | Cited on site | Coverage |",
        "|-------|------------:|--------------:|---------:|",
    ]
    for ex, d, c, pct in rows:
        lines.append(f"| {ex} | {d} | {c} | {pct:.0f}% |")
    lines.append(f"| **Total** | **{tot_det}** | **{tot_cov}** | **{overall:.1f}%** |")
    lines += ["", "## Not yet cited (per paper)", ""]
    for ex, missed in detail:
        lines.append(f"- **{ex}**: {', '.join(missed)}")
    (ROOT / "COVERAGE.md").write_text("\n".join(lines) + "\n", encoding="utf-8")

    summary = {
        "overall_pct": round(overall, 1), "cited": tot_cov, "detected": tot_det,
        "per_exam": [{"exam": ex, "det": d, "cit": c, "pct": round(p)} for ex, d, c, p in rows],
    }
    (ROOT / "data" / "coverage-summary.json").write_text(
        json.dumps(summary, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    print(f"wrote COVERAGE.md + data/coverage-summary.json — overall {tot_cov}/{tot_det} ({overall:.1f}%)")


if __name__ == "__main__":
    main()
